// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhLiMbl0Tl6-K9zHzMI9TklQZ0dAt6BD8',
    appId: '1:999975841782:web:0c05844b372359919ca1d7',
    messagingSenderId: '999975841782',
    projectId: 'sneakcom-97cb1',
    authDomain: 'sneakcom-97cb1.firebaseapp.com',
    storageBucket: 'sneakcom-97cb1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAedGFQwV6mZZX55of0mJp1AZieUh9Ho1I',
    appId: '1:999975841782:android:bb70bcd585b15c279ca1d7',
    messagingSenderId: '999975841782',
    projectId: 'sneakcom-97cb1',
    storageBucket: 'sneakcom-97cb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdLYUj_xkkOIy-XWOZltWlSl7loRU9k_0',
    appId: '1:999975841782:ios:584f4854493a4bb99ca1d7',
    messagingSenderId: '999975841782',
    projectId: 'sneakcom-97cb1',
    storageBucket: 'sneakcom-97cb1.firebasestorage.app',
    iosBundleId: 'com.example.sneakcomEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdLYUj_xkkOIy-XWOZltWlSl7loRU9k_0',
    appId: '1:999975841782:ios:584f4854493a4bb99ca1d7',
    messagingSenderId: '999975841782',
    projectId: 'sneakcom-97cb1',
    storageBucket: 'sneakcom-97cb1.firebasestorage.app',
    iosBundleId: 'com.example.sneakcomEcom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhLiMbl0Tl6-K9zHzMI9TklQZ0dAt6BD8',
    appId: '1:999975841782:web:13cd3786881a658b9ca1d7',
    messagingSenderId: '999975841782',
    projectId: 'sneakcom-97cb1',
    authDomain: 'sneakcom-97cb1.firebaseapp.com',
    storageBucket: 'sneakcom-97cb1.firebasestorage.app',
  );
}
